name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  mdGlob:
    required: true
    description: 'md files to test'
    default: '**/*.md'
runs:
  using: 'node16'
  main: 'dist/index.js'
